### ISSUE TITLE
Error when installing v0.5 without cython

### ISSUE THREAD

**Issue by mosquito** [coleifer/python-lsm-db#14]
```
Collecting lsm-db
  Downloading lsm-db-0.5.0.tar.gz (306kB)
    100% |████████████████████████████████| 307kB 1.4MB/s
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/lsm_db.egg-info
    writing pip-egg-info/lsm_db.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/lsm_db.egg-info/dependency_links.txt
    /private/var/folders/h0/60fpdchs4dv61n21mdynqh9h00r1ts/T/pip-build-radi5y9o/lsm-db/setup.py:10: UserWarning: Cython not installed, using pre-generated C source file.
      warnings.warn('Cython not installed, using pre-generated C source file.')
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/h0/60fpdchs4dv61n21mdynqh9h00r1ts/T/pip-build-radi5y9o/lsm-db/setup.py", line 32, in <module>
        ext_modules=cythonize([lsm_extension]),
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "env/lib/python3.6/site-packages/setuptools/command/egg_info.py", line 271, in run
        writer(self, ep.name, os.path.join(self.egg_info, ep.name))
      File "env/lib/python3.6/site-packages/setuptools/command/egg_info.py", line 652, in write_toplevel_names
        for k in cmd.distribution.iter_distribution_names()
      File "env/lib/python3.6/site-packages/setuptools/command/egg_info.py", line 651, in <listcomp>
        k.split('.', 1)[0]
      File "env/lib/python3.6/site-packages/setuptools/dist.py", line 820, in iter_distribution_names
        name = ext.name
    AttributeError: 'list' object has no attribute 'name'
```

**Comment by mosquito** [comment]
installing `lsm-db<0.5` works fine.

**Comment by coleifer** [comment]
Pushed 0.5.1
